services:
  app:
    networks: [default, web]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.todo.loadbalancer.server.port=80"
      - "traefik.http.routers.todo.rule=Host(`dibs.example.com`)"
      - "traefik.http.routers.todo.entrypoints=websecure"
      - "traefik.http.routers.todo.tls=true"
      - "traefik.http.routers.todo.middlewares=todo-lan"
      - "traefik.http.middlewares.todo-lan.ipallowlist.sourcerange=192.168.1.0/24,127.0.0.1/32,172.18.0.1/32"
      - "traefik.http.routers.todo-http.rule=Host(`dibs.example.com`)"
      - "traefik.http.routers.todo-http.entrypoints=web"
      - "traefik.http.routers.todo-http.middlewares=todo-lan,todo-https"
      - "traefik.http.middlewares.todo-https.redirectscheme.scheme=https"
networks:
  web:
    external: true
